// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKqiyOt-kpBwIZjZU7fiNOWJer2TK3Qjo',
    appId: '1:491986283499:web:b049639719ffdcbd8487ae',
    messagingSenderId: '491986283499',
    projectId: 'expanse-app-df481',
    authDomain: 'expanse-app-df481.firebaseapp.com',
    storageBucket: 'expanse-app-df481.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6DHUejDZ3QmtjCuDdxsguVM2oNgAbDCc',
    appId: '1:491986283499:android:ad05139b1be099278487ae',
    messagingSenderId: '491986283499',
    projectId: 'expanse-app-df481',
    storageBucket: 'expanse-app-df481.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdbDod3LBZO6SBK6Io59IM8CJB2BftRd0',
    appId: '1:491986283499:ios:28c6f5b2b14dda488487ae',
    messagingSenderId: '491986283499',
    projectId: 'expanse-app-df481',
    storageBucket: 'expanse-app-df481.appspot.com',
    iosClientId: '491986283499-5alib5fivd8r42dj6bgjs55413u3f5h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdbDod3LBZO6SBK6Io59IM8CJB2BftRd0',
    appId: '1:491986283499:ios:dd2b40618d4c2cee8487ae',
    messagingSenderId: '491986283499',
    projectId: 'expanse-app-df481',
    storageBucket: 'expanse-app-df481.appspot.com',
    iosClientId: '491986283499-0u9eomrdmth6cr8hhlb7osl44tgns64h.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingApp.RunnerTests',
  );
}
